import './sass/style.scss'
import './js_modules/video_section'
import './js_modules/gallery_section'
import './js_modules/buy_tickets'
import './js_modules/interactive_map'
import './js_modules/welcome_slider'
import './js_modules/burger'
import './js_modules/change_picture_slider'
